### ISSUE TITLE
Json注入

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [XiaoMi/thain#58]
https://github.com/XiaoMi/Thain/blob/b610792d35127704747c017ca41ba7d98d0f150c/thain-server/src/main/java/com/xiaomi/thain/server/controller/FlowController.java#L103-L106
应用程序所解析的JSON文档或请求来源于不可信赖的数据源，程序没有对这些不可信赖的数据进行验证、过滤，攻击者可以插入一些元素做一些可以预测的操作，比如解析JSON失败，导致抛出异常，甚至可以导致XSS和动态解析代码。

**Comment by liangyongrui** [comment]
Thanks for the feedback.

I will confirm the problem as soon as possible and fix it.

**Comment by liangyongrui** [comment]
I confirmed that there is no security issue here. If the code throws an exception, it is also caught and processed accordingly.

Is it possible to have a problem that I have not noticed, can you say it more clearly?
@QiAnXinCodeSafe
