### ISSUE TITLE
请问大佬们，支持延时Job吗

### ISSUE THREAD

**Issue by zhengdayday** [XiaoMi/thain#77]
有些场景定时任务不能满足或者说不太优雅，所以需要延时任务的功能

**Comment by liangyongrui** [comment]
延迟指的是 满足执行条件后 不立即执行， 然后等一段时间再执行？

**Comment by zhengdayday** [comment]
是的,比如aws 的sqs

**Comment by liangyongrui** [comment]
如果和嵌套flow结合，可以满足你吗？

如果满足某个条件，执行另一个flow

执行另一个的时候，可以选择：
1. 立即执行
1. 延迟x秒后执行

**Comment by liangyongrui** [comment]
经过沟通，可以通过 #81 #82  满足需求
